let tutorialTiles = [
    {shape: "straight", treasure: 0, rotation: 0, isDisplayed: true},
    {shape: "tShape", treasure: 10, rotation: 0, isDisplayed: true},
    {shape: "tShape", treasure: 14, rotation: 0, isDisplayed: true},
    {shape: "turn", treasure: 0, rotation: 1, isDisplayed: true},
    {shape: "turn", treasure: 1, rotation: 2, isDisplayed: true},
    {shape: "straight", treasure: 0, rotation: 1, isDisplayed: true},
    {shape: "turn", treasure: 0, rotation: 1, isDisplayed: true},
    {shape: "tShape", treasure: 13, rotation: 0, isDisplayed: true},
    {shape: "straight", treasure: 0, rotation: 1, isDisplayed: true},
    {shape: "straight", treasure: 0, rotation: 0, isDisplayed: true},
    {shape: "tShape", treasure: 5, rotation: 0, isDisplayed: true},
    {shape: "tShape", treasure: 6, rotation: 0, isDisplayed: true},
    {shape: "tShape", treasure: 15, rotation: 0, isDisplayed: true},
    {shape: "tShape", treasure: 7, rotation: 1, isDisplayed: true},
    {shape: "tShape", treasure: 11, rotation: 2, isDisplayed: true},
    {shape: "tShape", treasure: 16, rotation: 0, isDisplayed: true},
    {shape: "straight", treasure: 0, rotation: 0, isDisplayed: true},
    {shape: "turn", treasure: 0, rotation: 2, isDisplayed: true},
    {shape: "turn", treasure: 0, rotation: 1, isDisplayed: true},
    {shape: "turn", treasure: 8, rotation: 2, isDisplayed: true},
    {shape: "tShape", treasure: 12, rotation: 0, isDisplayed: true},
    {shape: "turn", treasure: 0, rotation: 0, isDisplayed: true},
    {shape: "tShape", treasure: 9, rotation: 1, isDisplayed: true},
    {shape: "tShape", treasure: 2, rotation: 1, isDisplayed: true},
    {shape: "straight", treasure: 0, rotation: 1, isDisplayed: true},
    {shape: "straight", treasure: 0, rotation: 2, isDisplayed: true},
    {shape: "tShape", treasure: 3, rotation: 2, isDisplayed: true},
    {shape: "turn", treasure: 0, rotation: 0, isDisplayed: true},
    {shape: "turn", treasure: 0, rotation: 0, isDisplayed: true},
    {shape: "tShape", treasure: 4, rotation: 0, isDisplayed: true},
    {shape: "straight", treasure: 0, rotation: 0, isDisplayed: true},
    {shape: "turn", treasure: 0, rotation: 0, isDisplayed: true}
]

export {tutorialTiles};